name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup mysql
      run: make mysql
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 ct
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run xref
      run: rebar3 xref
    - name: Cache dialyzer
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/rebar3/"
        key: rebar3-erl-22
